export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  EVENT_ADMIN = 'EVENT_ADMIN',
  AVENT_USER = 'AVENT_USER',
  CAN_ACC_DELETE = 'CAN_ACC_DELETE',
  CAN_ACC_VALIDATE = 'CAN_ACC_VALIDATE',
  CAN_ACC_AV_SEARCH = 'CAN_ACC_AV_SEARCH',
  CAN_ACC_MASS_UPDATE = 'CAN_ACC_MASS_UPDATE',
  CAN_ACC_IMPORT = 'CAN_ACC_IMPORT',
  CAN_ACC_ACTIVAT = 'CAN_ACC_ACTIVAT',
}
