# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  sigmaevents-app:
    image: sigmaevents
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://sigmaeventsdbserver.mysql.database.azure.com:3306/sigmaevents?serverTimezone=UTC
      - SPRING_LIQUIBASE_URL=jdbc:mysql://sigmaevents-mysql:3306/sigmaevents?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 80
