INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("FRMF", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("TEAM", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("CA", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("LOC", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("PRESSE", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("BROADCASTER", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("SECURITY", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("SERVICES", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("VOLUNTEERS", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("comité d`organisation", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("AUTORITES", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("GDR", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("comité directeur", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("président frmf", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("secrétaire général", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("adj secrétaire général", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("acc arbitres", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("FRMF Guests", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("POLICE", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("MJS", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("STAFF WAC", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("sponsoring", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("Medicale", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("comité executif", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("test", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("F.A.R", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("LMFP", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("secrétaire général LNFP", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("secrétaire général LNFA", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("SG-LNFP", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("Préfet de police", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("superviseur", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("commissaire au match", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("invité police", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("invité", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("GUINEA ECUATORIAL", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("DTN", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("catering salon royal", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("Catering", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("STAFF EQUIPE NATIONALE", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("SELECTIONNEUR NATIONAL", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("SELECTIONNEUR NATIONALE ADJ", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("PRÉPARATEUR PHYSIQUE", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("ENTRAîNEUR DES GARDIENS", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("WILAYA", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("ONCF", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("LNFP", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("VICE-Président", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("AMBASSADEUR", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("MANAGER", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("fédération burkinabè de football", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("Président de la CAF", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("Conseiller", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("conseiller du president", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("commission", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("COORDINATeur", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("competition", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("ADMINISTRATION ", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("SECURITE & ACCUEIL", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("PROTOCOLE", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("Loc CATERING", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("ACCREDITATION & IT", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("MARKETING", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("broadcast", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("MEDIA", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("LOGISTIQUE", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("FINANCE", true, 3);
INSERT INTO sigmaevents.category(category_name,category_stat,event_event_id) VALUES("DGSN", true, 3);
