INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Observer Programs","#ffffff",15,"OBS",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Match Officials","#ffffff",15,"REF",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Delegation Members","#ffffff",15,"COE",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Guests","#ffffff",15,"GUE",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Marketing Hospitality","#ffffff",15,"MHS",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("PROTOCOLE","#ffffff",15,"PRT",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("sponsoring","#ffffff",15,"spr",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("dev int","#ffffff",15,"dev",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("DTN","#ffffff",15,"DTN001",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Teams (Players)","#ffffff",49,"TEAM",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Teams (Officials)","#ffffff",49,"TEAM",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Teams (Team Media Officer)","#ffffff",49,"TEAM",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Partner","#ffffff",50,"PAR",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Official Licensee","#ffffff",50,"LIC",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("National Supporter","#ffffff",50,"SUP",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("LOC Staff","#ffffff",18,"LOC",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("LOC Guests","#ffffff",18,"INV",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("superviseur","#ffffff",18,"frmf",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("UNAF-LOC","#ffffff",18,"UNAF-LOC",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("superviseur 1","#ffffff",18,"frmf",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("LOC DRIVER","#ffffff",18,"LOD01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("International Press","#ffffff",19,"PRE",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("International Photographer","#ffffff",19,"PHO",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Local Press","#ffffff",19,"PRE",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Local Photographer","#ffffff",19,"PHO",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Technicians Photo Press","#ffffff",19,"TPP",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("TV Radio","#ffffff",19,"NRH",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("TV Radio 2","#ffffff",19,"NRH2",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Host Broadcaster","#ffffff",20,"HB",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("TV Radio Media Rights Licensee","#ffffff",20,"RTV",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Host Broadcaster all","#ffffff",20,"HB",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Security Personnel","#ffffff",21,"SEC",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Security Personnel 1","#ffffff",21,"SEC2",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("sec VIP","#ffffff",21,"SECV",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Kara 1","#ffffff",21,"Sec001",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("kara 2","#ffffff",21,"sec002",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("kara 3","#ffffff",21,"sec003",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Security Personnel 2","#ffffff",21,"SEC3",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("SEC 234","#ffffff",21,"SEC03",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Security Personnel 3","#ffffff",21,"SEC3",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Ticketing","#ffffff",22,"SERV01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Sound System Maintenance","#ffffff",22,"SERV02",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Stadium Maintenance","#ffffff",22,"SERV03",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("IT Maintenance","#ffffff",22,"SERV04",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Vendor","#ffffff",22,"SERV05",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("HOTESS","#ffffff",22,"SERV06",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Stadium Staff","#ffffff",22,"SERV07",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Driver","#ffffff",22,"SERV08",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("FRMFM Services","#ffffff",22,"SERV",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Catering","#ffffff",22,"SERV09",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Ticketing","#ffffff",22,"SERV01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("media","#ffffff",22,"SERV10",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("sponsore","#ffffff",22,"spn",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("matchday crew","#ffffff",22,"mdc",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("spb","#ffffff",22,"spb",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Staff Stade 2","#ffffff",22,"STF07",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Staff Stade 3","#ffffff",22,"SERV12",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("accreditation","#ffffff",22,"acr",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("maintenance 2","#ffffff",22,"SERV126",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("HLO","#ffffff",22,"SERV013",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("compa","#ffffff",22,"COM001",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Stadium Staff palais","#ffffff",22,"ser011",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("F.Menage","#ffffff",22,"fME",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("F.Menage Presse","#ffffff",22,"FMEP",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("F.Menage TR","#ffffff",22,"FMTR",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Match day Crew","#ffffff",22,"MDC",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Catering 2","#ffffff",22,"SERV09",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Staff Stade 4","#ffffff",22,"SERV15",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("roads","#ffffff",22,"RDS",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("STAFF STAD 5","#ffffff",22,"STF05",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("superviseur","#ffffff",22,"SERV16",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("SERVICES SUPERVISEUR","#ffffff",22,"SERV018",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("HOTESS MEDIA","#ffffff",22,"SERV019",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("STAFF STAD 6","#ffffff",22,"STF05",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Service Media","#ffffff",22,"SERV08",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("STAFF STAD 7","#ffffff",22,"STF07",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Protocol Volunteers","#ffffff",23,"VOL01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Accreditation Volunteers","#ffffff",23,"VOL02",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Media Volunteers","#ffffff",23,"VOL03",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Transportation Volunteers","#ffffff",23,"VOL04",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Matchday Crew v","#ffffff",23,"VOL05",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Ticketing Volunteers","#ffffff",23,"VOL06",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Marketing Hospitality-v","#ffffff",23,"VOL07",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Medical Volunteers","#ffffff",23,"VOL08",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("VOL TANGER","#ffffff",23,"VOLT01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("PARKING VOLUNTEERS","#ffffff",23,"VOL005",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("aut1","#ffffff",25,"aut",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("aut2","#ffffff",25,"aut",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("aut3","#ffffff",25,"aut",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("gdr","#ffffff",26,"gdr",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("gdr2","#ffffff",26,"gdr02",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("gdr3","#ffffff",26,"gdr03",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("frmf","#ffffff",27,"frmf",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("président frmf","#ffffff",28,"frmf",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("sec frmf","#ffffff",29,"frmf",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("adj sec frmf","#ffffff",30,"frmf",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("accompagnateur","#ffffff",31,"acc01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("FRMF Guests","#ffffff",32,"frmf001",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("POCILE agadir","#ffffff",33,"PO02",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("police agadir 2","#ffffff",33,"POL002",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Police Casablanca","#ffffff",33,"POL03",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("police tanger","#ffffff",33,"pol03",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("police 1234","#ffffff",33,"pol04",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("test","#ffffff",34,"3",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("MJS","#ffffff",34,"MJS01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("WAC","#ffffff",35,"STW",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("ALQUDRA","#ffffff",36,"SPR",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("staff Medicale","#ffffff",37,"MED01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("staff Medicale 2","#ffffff",37,"MS",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("staff Medicale 3","#ffffff",37,"MS",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("UNAF","#ffffff",38,"UNAF-CE",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("test1","#ffffff",39,"tst",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("test2","#ffffff",39,"t2",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("FAR1","#ffffff",40,"FAR01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("FAR2","#ffffff",40,"FAR02",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("LNFP1","#ffffff",41,"LNFP",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("LNFP","#ffffff",42,"LNFA",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("LNFP","#ffffff",42,"LNFA",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("police","#ffffff",45,"POL04",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("superviseur all","#ffffff",46,"SUP01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("com1","#ffffff",47,"COM01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("invité","#ffffff",48,"IPO01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("invité police","#ffffff",49,"IPO01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("invité ministere","#ffffff",49,"IMO01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Team","#ffffff",50,"GU.E",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("DTN ALL ","#ffffff",51,"DTN01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("DTN 2","#ffffff",51,"DTN02",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("cat 5 9 ","#ffffff",52,"cat01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("salon royal","#ffffff",52,"cat01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("STAFF 01","#ffffff",53,"SEN01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("STAFF 02","#ffffff",54,"SEN01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("STAFF 03","#ffffff",55,"SEN01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("WILAYA1","#ffffff",59,"WL001",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("ONCF01","#ffffff",60,"ONC001",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("LNFP ALL","#ffffff",61,"LN001",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("VP","#ffffff",62,"VP01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("AMB","#ffffff",63,"AMB01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("FBB","#ffffff",65,"FB01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("Président","#ffffff",66,"PCAF01",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("FRMF","#ffffff",68,"Consfrmf",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("commission frmf","#ffffff",69,"comfrmf",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("COORDINATeur","#ffffff",70,"CORDI",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc coordinateur","#ffffff",70,"CORDI",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc competition","#ffffff",71,"COMP",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc ADMINISTRATION","#ffffff",72,"LOCA",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc SECURITE & ACCUEIL","#ffffff",73,"SECACC",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc PROTOCOLE","#ffffff",74,"lPRO",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc CATERING","#ffffff",75,"lcat",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc ACCREDITATION IT","#ffffff",76,"LACCIT",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc MARKETING","#ffffff",77,"lcmark",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc broadcast","#ffffff",78,"lcbro",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("LOC MEDIA","#ffffff",79,"lcmed",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc LOGISTIQUE","#ffffff",80,"lclog",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc FINANCE","#ffffff",81,"locfin",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("loc FINANCE","#ffffff",81,"LOCFIN",true, 3);
INSERT INTO sigmaevents.fonction(fonction_name,fonction_color,category_category_id,fonction_abreviation,fonction_stat,event_event_id) VALUES("DGSN","#ffffff",82,"DGSN",true, 3);
