INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Afghan	","	AF	","	Afghanistan	","	AFG	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Island Island	","	AX	","	Island Islands	","	ALA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Albanian	","	AL	","	Albania	","	ALB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Algerian	","	DZ	","	Algeria	","	DZA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	American Samoan	","	AS	","	American Samoa	","	ASM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Andorran	","	AD	","	Andorra	","	AND	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Angolan	","	AO	","	Angola	","	AGO	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Anguillan	","	AI	","	Anguilla	","	AIA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Antarctic	","	AQ	","	Antarctica	","	ATA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Antiguan or Barbudan	","	AG	","	Antigua and Barbuda	","	ATG	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Argentine	","	AR	","	Argentina	","	ARG	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Armenian	","	AM	","	Armenia	","	ARM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Aruban	","	AW	","	Aruba	","	ABW	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Australian	","	AU	","	Australia	","	AUS	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Austrian	","	AT	","	Austria	","	AUT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Azerbaijani	","	AZ	","	Azerbaijan	","	AZE	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bahamian	","	BS	","	Bahamas	","	BHS	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bahraini	","	BH	","	Bahrain	","	BHR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bangladeshi	","	BD	","	Bangladesh	","	BGD	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Barbadian	","	BB	","	Barbados	","	BRB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Belarusian	","	BY	","	Belarus	","	BLR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Belgian	","	BE	","	Belgium	","	BEL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Belizean	","	BZ	","	Belize	","	BLZ	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Beninois	","	BJ	","	Benin	","	BEN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bermudan	","	BM	","	Bermuda	","	BMU	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bhutanese	","	BT	","	Bhutan	","	BTN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bolivian	","	BO	","	Bolivia	","	BOL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bonaire	","	BQ	","	Bonaire	","	BES	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bosnian or Herzegovinian	","	BA	","	Bosnia and Herzegovina	","	BIH	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Botswanan	","	BW	","	Botswana	","	BWA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bouvet Island	","	BV	","	Bouvet Island	","	BVT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Brazilian	","	BR	","	Brazil	","	BRA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	BIOT	","	IO	","	British Indian Ocean Territory	","	IOT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bruneian	","	BN	","	Brunei Darussalam	","	BRN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bulgarian	","	BG	","	Bulgaria	","	BGR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Burkinabi	","	BF	","	Burkina Faso	","	BFA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Burundian	","	BI	","	Burundi	","	BDI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Cabo Verdean	","	CV	","	Cabo Verde	","	CPV	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Cambodian	","	KH	","	Cambodia	","	KHM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Cameroonian	","	CM	","	Cameroon	","	CMR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Canadian	","	CA	","	Canada	","	CAN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Caymanian	","	KY	","	Cayman Islands	","	CYM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Central African	","	CF	","	Central African Republic	","	CAF	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Chadian	","	TD	","	Chad	","	TCD	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Chilean	","	CL	","	Chile	","	CHL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Chinese	","	CN	","	China	","	CHN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Christmas Island	","	CX	","	Christmas Island	","	CXR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Cocos Island	","	CC	","	Cocos	","	CCK	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Colombian	","	CO	","	Colombia	","	COL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Comorian	","	KM	","	Comoros	","	COM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Congolese	","	CG	","	Congo	","	COG	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Congolese	","	CD	","	Congo	","	COD	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Cook Island	","	CK	","	Cook Islands	","	COK	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Costa Rican	","	CR	","	Costa Rica	","	CRI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Ivorian	","	CI	","	Cote d'Ivoire	","	CIV	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Croatian	","	HR	","	Croatia	","	HRV	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Cuban	","	CU	","	Cuba	","	CUB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Curasaoan	","	CW	","	Curasao	","	CUW	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Cypriot	","	CY	","	Cyprus	","	CYP	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Czech	","	CZ	","	Czech Republic	","	CZE	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Danish	","	DK	","	Denmark	","	DNK	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Djiboutian	","	DJ	","	Djibouti	","	DJI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Dominican	","	DM	","	Dominica	","	DMA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Dominican	","	DO	","	Dominican Republic	","	DOM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Ecuadorian	","	EC	","	Ecuador	","	ECU	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Egyptian	","	EG	","	Egypt	","	EGY	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Salvadoran	","	SV	","	El Salvador	","	SLV	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Equatoguinean	","	GQ	","	Equatorial Guinea	","	GNQ	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Eritrean	","	ER	","	Eritrea	","	ERI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Estonian	","	EE	","	Estonia	","	EST	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Ethiopian	","	ET	","	Ethiopia	","	ETH	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Falkland Island	","	FK	","	Falkland Islands	","	FLK	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Faroese	","	FO	","	Faroe Islands	","	FRO	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Fijian	","	FJ	","	Fiji	","	FJI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Finnish	","	FI	","	Finland	","	FIN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	French	","	FR	","	France	","	FRA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	French Guianese	","	GF	","	French Guiana	","	GUF	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	French Polynesian	","	PF	","	French Polynesia	","	PYF	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	French Southern Territories	","	TF	","	French Southern Territories	","	ATF	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Gabonese	","	GA	","	Gabon	","	GAB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Gambian	","	GM	","	Gambia	","	GMB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Georgian	","	GE	","	Georgia	","	GEO	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	German	","	DE	","	Germany	","	DEU	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Ghanaian	","	GH	","	Ghana	","	GHA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Gibraltar	","	GI	","	Gibraltar	","	GIB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Greek	","	GR	","	Greece	","	GRC	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Greenlandic	","	GL	","	Greenland	","	GRL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Grenadian	","	GD	","	Grenada	","	GRD	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Guadeloupe	","	GP	","	Guadeloupe	","	GLP	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Guamanian	","	GU	","	Guam	","	GUM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Guatemalan	","	GT	","	Guatemala	","	GTM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Channel Island	","	GG	","	Guernsey	","	GGY	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Guinean	","	GN	","	Guinea	","	GIN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Bissau-Guinean	","	GW	","	Guinea-Bissau	","	GNB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Guyanese	","	GY	","	Guyana	","	GUY	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Haitian	","	HT	","	Haiti	","	HTI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Heard Island or McDonald Islands	","	HM	","	Heard Island and McDonald Islands	","	HMD	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Vatican	","	VA	","	Vatican City State	","	VAT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Honduran	","	HN	","	Honduras	","	HND	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Hong Kong	","	HK	","	Hong Kong	","	HKG	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Hungarian	","	HU	","	Hungary	","	HUN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Icelandic	","	IS	","	Iceland	","	ISL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Indian	","	IN	","	India	","	IND	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Indonesian	","	ID	","	Indonesia	","	IDN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Iranian	","	IR	","	Iran	","	IRN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Iraqi	","	IQ	","	Iraq	","	IRQ	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Irish	","	IE	","	Ireland	","	IRL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Manx	","	IM	","	Isle of Man	","	IMN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Israeli	","	IL	","	Israel	","	ISR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Italian	","	IT	","	Italy	","	ITA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Jamaican	","	JM	","	Jamaica	","	JAM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Japanese	","	JP	","	Japan	","	JPN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Channel Island	","	JE	","	Jersey	","	JEY	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Jordanian	","	JO	","	Jordan	","	JOR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Kazakhstani	","	KZ	","	Kazakhstan	","	KAZ	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Kenyan	","	KE	","	Kenya	","	KEN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	I-Kiribati	","	KI	","	Kiribati	","	KIR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	North Korean	","	KP	","	Korea	","	PRK	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	South Korean	","	KR	","	Korea	","	KOR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Kuwaiti	","	KW	","	Kuwait	","	KWT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Kyrgyzstani	","	KG	","	Kyrgyzstan	","	KGZ	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Laotian	","	LA	","	Lao People's Democratic Republic	","	LAO	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Latvian	","	LV	","	Latvia	","	LVA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Lebanese	","	LB	","	Lebanon	","	LBN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Basotho	","	LS	","	Lesotho	","	LSO	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Liberian	","	LR	","	Liberia	","	LBR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Libyan	","	LY	","	Libya	","	LBY	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Liechtenstein	","	LI	","	Liechtenstein	","	LIE	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Lithuanian	","	LT	","	Lithuania	","	LTU	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Luxembourgish	","	LU	","	Luxembourg	","	LUX	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Macanese	","	MO	","	Macao	","	MAC	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Macedonian	","	MK	","	Macedonia	","	MKD	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Malagasy	","	MG	","	Madagascar	","	MDG	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Malawian	","	MW	","	Malawi	","	MWI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Malaysian	","	MY	","	Malaysia	","	MYS	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Maldivian	","	MV	","	Maldives	","	MDV	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Malian	","	ML	","	Mali	","	MLI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Maltese	","	MT	","	Malta	","	MLT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Marshallese	","	MH	","	Marshall Islands	","	MHL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Martinican	","	MQ	","	Martinique	","	MTQ	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Mauritanian	","	MR	","	Mauritania	","	MRT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Mauritian	","	MU	","	Mauritius	","	MUS	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Mahoran	","	YT	","	Mayotte	","	MYT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Mexican	","	MX	","	Mexico	","	MEX	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Micronesian	","	FM	","	Micronesia	","	FSM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Moldovan	","	MD	","	Moldova	","	MDA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Monacan	","	MC	","	Monaco	","	MCO	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Mongolian	","	MN	","	Mongolia	","	MNG	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Montenegrin	","	ME	","	Montenegro	","	MNE	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Montserratian	","	MS	","	Montserrat	","	MSR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Moroccan	","	MA	","	Morocco	","	MAR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Mozambican	","	MZ	","	Mozambique	","	MOZ	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Burmese	","	MM	","	Myanmar	","	MMR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Namibian	","	NA	","	Namibia	","	NAM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Nauruan	","	NR	","	Nauru	","	NRU	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Nepali	","	NP	","	Nepal	","	NPL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Dutch	","	NL	","	Netherlands	","	NLD	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	New Caledonian	","	NC	","	New Caledonia	","	NCL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	New Zealand, NZ	","	NZ	","	New Zealand	","	NZL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Nicaraguan	","	NI	","	Nicaragua	","	NIC	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Nigerien	","	NE	","	Niger	","	NER	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Nigerian	","	NG	","	Nigeria	","	NGA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Niuean	","	NU	","	Niue	","	NIU	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Norfolk Island	","	NF	","	Norfolk Island	","	NFK	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Northern Marianan	","	MP	","	Northern Mariana Islands	","	MNP	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Norwegian	","	NO	","	Norway	","	NOR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Omani	","	OM	","	Oman	","	OMN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Pakistani	","	PK	","	Pakistan	","	PAK	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Palauan	","	PW	","	Palau	","	PLW	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Palestinian	","	PS	","	Palestine	","	PSE	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Panamanian	","	PA	","	Panama	","	PAN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Papua New Guinean	","	PG	","	Papua New Guinea	","	PNG	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Paraguayan	","	PY	","	Paraguay	","	PRY	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Peruvian	","	PE	","	Peru	","	PER	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Philippine	","	PH	","	Philippines	","	PHL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Pitcairn Island	","	PN	","	Pitcairn	","	PCN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Polish	","	PL	","	Poland	","	POL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Portuguese	","	PT	","	Portugal	","	PRT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Puerto Rican	","	PR	","	Puerto Rico	","	PRI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Qatari	","	QA	","	Qatar	","	QAT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Réunionnais	","	RE	","	Réunion	","	REU	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Romanian	","	RO	","	Romania	","	ROU	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Russian	","	RU	","	Russian Federation	","	RUS	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Rwandan	","	RW	","	Rwanda	","	RWA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	BarthÃ©lemois	","	BL	","	Saint Barthlemy	","	BLM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Saint Helenian	","	SH	","	Saint Helena	","	SHN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Kittitian or Nevisian	","	KN	","	Saint Kitts and Nevis	","	KNA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Saint Lucian	","	LC	","	Saint Lucia	","	LCA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Saint-Martinoise	","	MF	","	Saint Martin	","	MAF	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Saint-Pierrais or Miquelonnais	","	PM	","	Saint Pierre and Miquelon	","	SPM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Vincentian	","	VC	","	Saint Vincent and the Grenadines	","	VCT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Samoan	","	WS	","	Samoa	","	WSM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Sammarinese	","	SM	","	San Marino	","	SMR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Sao Toman	","	ST	","	Sao Tome and Principe	","	STP	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Saudi Arabian	","	SA	","	Saudi Arabia	","	SAU	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Senegalese	","	SN	","	Senegal	","	SEN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Serbian	","	RS	","	Serbia	","	SRB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Seychellois	","	SC	","	Seychelles	","	SYC	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Sierra Leonean	","	SL	","	Sierra Leone	","	SLE	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Singaporean	","	SG	","	Singapore	","	SGP	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Sint Maarten	","	SX	","	Sint Maarten	","	SXM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Slovak	","	SK	","	Slovakia	","	SVK	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Slovenian	","	SI	","	Slovenia	","	SVN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Solomon Island	","	SB	","	Solomon Islands	","	SLB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Somalian	","	SO	","	Somalia	","	SOM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	South African	","	ZA	","	South Africa	","	ZAF	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	South Georgia or South Sandwich Islands	","	GS	","	South Georgia and the South Sandwich Islands	","	SGS	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	South Sudanese	","	SS	","	South Sudan	","	SSD	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Spanish	","	ES	","	Spain	","	ESP	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Sri Lankan	","	LK	","	Sri Lanka	","	LKA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Sudanese	","	SD	","	Sudan	","	SDN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Surinamese	","	SR	","	Suriname	","	SUR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Svalbard	","	SJ	","	Svalbard and Jan Mayen	","	SJM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Swazi	","	SZ	","	Swaziland	","	SWZ	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Swedish	","	SE	","	Sweden	","	SWE	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Swiss	","	CH	","	Switzerland	","	CHE	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Syrian	","	SY	","	Syrian Arab Republic	","	SYR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Taiwanese	","	TW	","	Taiwan	","	TWN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Tajikistani	","	TJ	","	Tajikistan	","	TJK	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Tanzanian	","	TZ	","	Tanzania	","	TZA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Thai	","	TH	","	Thailand	","	THA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Timorese	","	TL	","	Timor-Leste	","	TLS	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Togolese	","	TG	","	Togo	","	TGO	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Tokelauan	","	TK	","	Tokelau	","	TKL	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Tongan	","	TO	","	Tonga	","	TON	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Trinidadian or Tobagonian	","	TT	","	Trinidad and Tobago	","	TTO	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Tunisian	","	TN	","	Tunisia	","	TUN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Turkish	","	TR	","	Turkey	","	TUR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Turkmen	","	TM	","	Turkmenistan	","	TKM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Turks and Caicos Island	","	TC	","	Turks and Caicos Islands	","	TCA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Tuvaluan	","	TV	","	Tuvalu	","	TUV	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Ugandan	","	UG	","	Uganda	","	UGA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Ukrainian	","	UA	","	Ukraine	","	UKR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Emirati	","	AE	","	United Arab Emirates	","	ARE	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	British, UK	","	GB	","	United Kingdom of Great Britain and Northern Ireland	","	GBR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	American	","	UM	","	United States Minor Outlying Islands	","	UMI	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	American	","	US	","	United States of America	","	USA	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Uruguayan	","	UY	","	Uruguay	","	URY	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Uzbekistani	","	UZ	","	Uzbekistan	","	UZB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Ni-Vanuatu	","	VU	","	Vanuatu	","	VUT	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Venezuelan	","	VE	","	Venezuela 	","	VEN	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Vietnamese	","	VN	","	Vietnam	","	VNM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	British Virgin Island	","	VG	","	Virgin Islands (British)	","	VGB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	U.S. Virgin Island	","	VI	","	Virgin Islands (U.S.)	","	VIR	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Wallis and Futuna	","	WF	","	Wallis and Futuna	","	WLF	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Yemeni	","	YE	","	Yemen	","	YEM	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Zambian	","	ZM	","	Zambia	","	ZMB	",true);
INSERT INTO sigmaevents.nationality(nationality_value,nationality_abreviation,nationality_description,nationality_params,nationality_stat) VALUES	("	Zimbabwean	","	ZW	","	Zimbabwe	","	ZWE	",true);
